name: clutch_ai
description: A proactive productivity companion.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  google_sign_in: ^6.2.1  
  shared_preferences: ^2.2.3